/**
 * seed.js — Database Seeder (MongoDB / Mongoose)
 *
 * OOSE Concept: Single Responsibility
 *   - This module's sole job is to populate the database with initial data.
 *   - Hospitals are inserted first, then Doctors embed Hospital ObjectIds.
 */
require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const connectDB          = require('../config/database');
const { Doctor, Hospital } = require('../models');

// ── Seed data ─────────────────────────────────────────────────────────────────
const hospitalData = [
  { slug: 'h01', name: 'Apollo Hospitals',         address: '21 Greams Lane, Chennai',                    emergency: true,  latitude: 13.060, longitude: 80.237, phone: '+91-44-2829-0200',    rating: 4.7, beds: 500,  type: 'Multi-Specialty',        facilities: ['ICU','NICU','Dialysis','MRI','CT Scan','Pharmacy','Blood Bank'] },
  { slug: 'h02', name: 'Fortis Healthcare',         address: 'Sector 62, Noida',                           emergency: true,  latitude: 28.627, longitude: 77.371, phone: '+91-120-496-1000',    rating: 4.5, beds: 300,  type: 'Multi-Specialty',        facilities: ['ICU','OT','Blood Bank','Radiology','Physiotherapy'] },
  { slug: 'h03', name: 'Max Super Speciality',      address: 'Press Enclave Road, Saket, Delhi',           emergency: true,  latitude: 28.529, longitude: 77.221, phone: '+91-11-2651-5050',    rating: 4.6, beds: 400,  type: 'Super Speciality',       facilities: ['Cardiology','Neurology','Oncology','Transplant','Robotics'] },
  { slug: 'h04', name: 'Kokilaben Hospital',        address: 'Rao Saheb Achutrao Patwardhan Marg, Mumbai', emergency: true,  latitude: 19.130, longitude: 72.823, phone: '+91-22-4269-6969',    rating: 4.8, beds: 750,  type: 'Multi-Specialty',        facilities: ['Robotic Surgery','NICU','Proton Therapy','MRI','PET Scan','Cath Lab'] },
  { slug: 'h05', name: 'Lilavati Hospital',         address: 'A-791, Bandra Reclamation, Mumbai',          emergency: false, latitude: 19.050, longitude: 72.832, phone: '+91-22-2675-1000',    rating: 4.4, beds: 350,  type: 'General',                facilities: ['OPD','Emergency','Radiology','Pharmacy','Pathology'] },
  { slug: 'h06', name: 'Hinduja Hospital',          address: 'Veer Savarkar Marg, Mahim, Mumbai',          emergency: true,  latitude: 19.032, longitude: 72.838, phone: '+91-22-2445-1515',    rating: 4.9, beds: 400,  type: 'Multi-Specialty',        facilities: ['ICU','Cath Lab','Blood Bank','Pharmacy','Dialysis'] },
  { slug: 'h07', name: 'Tata Memorial Centre',      address: 'Dr. E Borges Road, Parel, Mumbai',           emergency: true,  latitude: 19.006, longitude: 72.840, phone: '+91-22-2417-7000',    rating: 4.9, beds: 600,  type: 'Oncology Specialty',     facilities: ['Radiation Oncology','Surgery','PET Scan','Chemotherapy','Immunotherapy'] },
  { slug: 'h08', name: 'Nanavati Super Speciality', address: 'SV Road, Vile Parle, Mumbai',                emergency: true,  latitude: 19.098, longitude: 72.842, phone: '+91-22-2626-7500',    rating: 4.6, beds: 350,  type: 'Multi-Specialty',        facilities: ['Neurosciences','Orthopedics','MRI','Dialysis','NICU'] },
  { slug: 'h09', name: 'AIIMS New Delhi',            address: 'Sri Aurobindo Marg, Ansari Nagar, Delhi',   emergency: true,  latitude: 28.568, longitude: 77.210, phone: '+91-11-2658-8500',    rating: 5.0, beds: 2500, type: 'Government Teaching',    facilities: ['All Specialities','Research','Emergency','Trauma Centre','Blood Bank'] },
  { slug: 'h10', name: 'Manipal Hospital',           address: '#98, HAL Airport Road, Bangalore',           emergency: true,  latitude: 12.959, longitude: 77.649, phone: '+91-80-2502-4444',    rating: 4.7, beds: 650,  type: 'Multi-Specialty',        facilities: ['Cardiology','Neurology','Oncology','Orthopedics','Transplant','ICU'] },
  { slug: 'h11', name: 'Christian Medical College', address: 'Ida Scudder Road, Vellore, Tamil Nadu',      emergency: true,  latitude: 12.932, longitude: 79.133, phone: '+91-416-228-4272',    rating: 4.8, beds: 900,  type: 'Teaching Hospital',      facilities: ['All Specialities','Research Labs','Emergency','Dermatology','ENT'] },
  { slug: 'h12', name: 'Medanta — The Medicity',    address: 'Sector 38, Gurugram, Haryana',               emergency: true,  latitude: 28.440, longitude: 77.026, phone: '+91-124-414-1414',    rating: 4.8, beds: 1250, type: 'Centre of Excellence',   facilities: ['Heart Institute','Neuro Centre','Oncology','Orthopedics','NICU','Robotics'] },
];

// Each doctor entry lists hospital slugs + schedule
const doctorData = [
  { name: 'Dr. Arjun Mehta',     specialization: 'Cardiologist',       experience: 18, education: 'MBBS, MD (Cardiology) — AIIMS Delhi',             rating: 4.9, reviews_count: 512,  latitude: 28.568, longitude: 77.210, phone: '+91-98765-43210', consultation_fee: 1200, bio: 'Pioneer in minimally invasive cardiac surgery with 18 years at AIIMS.',                                languages: ['English','Hindi'],            hospitalSlots: [{ slug:'h09', visiting_days:['Mon','Wed','Fri'],           timing:'09:00 AM - 01:00 PM' }, { slug:'h12', visiting_days:['Tue','Thu'],                 timing:'03:00 PM - 07:00 PM' }] },
  { name: 'Dr. Priya Sharma',    specialization: 'Neurologist',         experience: 14, education: 'MBBS, DM (Neurology) — PGI Chandigarh',            rating: 4.8, reviews_count: 345,  latitude: 28.627, longitude: 77.371, phone: '+91-98765-43211', consultation_fee: 1000, bio: 'Expert in migraine management, Parkinson\'s, epilepsy, and stroke care.',                               languages: ['English','Hindi','Punjabi'],  hospitalSlots: [{ slug:'h02', visiting_days:['Mon','Tue','Wed'],           timing:'10:00 AM - 02:00 PM' }, { slug:'h03', visiting_days:['Thu','Sat'],                 timing:'04:00 PM - 08:00 PM' }] },
  { name: 'Dr. Rohan Kapoor',    specialization: 'Orthopedist',         experience: 20, education: 'MBBS, MS (Ortho) — KEM Mumbai',                    rating: 4.7, reviews_count: 298,  latitude: 19.130, longitude: 72.823, phone: '+91-98765-43212', consultation_fee: 900,  bio: 'Joint replacement specialist. Performed 3000+ knee and hip replacements.',                             languages: ['English','Hindi','Marathi'],  hospitalSlots: [{ slug:'h04', visiting_days:['Mon','Wed','Fri'],           timing:'09:00 AM - 12:00 PM' }, { slug:'h08', visiting_days:['Tue','Thu','Sat'],           timing:'02:00 PM - 06:00 PM' }] },
  { name: 'Dr. Sunita Rao',      specialization: 'Dermatologist',       experience: 12, education: 'MBBS, MD (Dermatology) — Manipal University',      rating: 4.6, reviews_count: 267,  latitude: 12.959, longitude: 77.649, phone: '+91-98765-43213', consultation_fee: 700,  bio: 'Specializes in cosmetic dermatology, laser treatments, psoriasis, and autoimmune skin conditions.',    languages: ['English','Kannada','Telugu'], hospitalSlots: [{ slug:'h10', visiting_days:['Mon','Wed','Fri'],           timing:'11:00 AM - 03:00 PM' }, { slug:'h11', visiting_days:['Tue','Thu'],                 timing:'09:00 AM - 12:00 PM' }] },
  { name: 'Dr. Vijay Nair',      specialization: 'Gastroenterologist',  experience: 16, education: 'MBBS, DM (Gastro) — JIPMER Puducherry',            rating: 4.8, reviews_count: 320,  latitude: 19.050, longitude: 72.832, phone: '+91-98765-43214', consultation_fee: 1100, bio: 'Advanced endoscopy specialist. Expert in liver diseases, IBD, and pancreatic disorders.',              languages: ['English','Malayalam','Tamil'],hospitalSlots: [{ slug:'h05', visiting_days:['Mon','Wed','Fri'],           timing:'10:00 AM - 01:00 PM' }, { slug:'h06', visiting_days:['Tue','Thu','Sat'],           timing:'03:00 PM - 07:00 PM' }] },
  { name: 'Dr. Kavya Iyer',      specialization: 'Pediatrician',        experience: 11, education: 'MBBS, MD (Pediatrics) — Kasturba Medical College',  rating: 4.9, reviews_count: 630,  latitude: 12.932, longitude: 79.133, phone: '+91-98765-43215', consultation_fee: 600,  bio: 'Dedicated to child health from newborns to adolescents. Specialist in neonatal care.',                languages: ['English','Tamil','Malayalam'],hospitalSlots: [{ slug:'h11', visiting_days:['Mon','Tue','Wed','Thu','Fri'],timing:'08:00 AM - 12:00 PM' }, { slug:'h10', visiting_days:['Sat'],                      timing:'10:00 AM - 01:00 PM' }] },
  { name: 'Dr. Amit Joshi',      specialization: 'Pulmonologist',       experience: 13, education: 'MBBS, MD (Pulmonology) — AIIMS Jodhpur',            rating: 4.5, reviews_count: 234,  latitude: 28.440, longitude: 77.026, phone: '+91-98765-43216', consultation_fee: 850,  bio: 'Specialist in asthma, COPD, sleep apnea, and interstitial lung diseases.',                            languages: ['English','Hindi','Gujarati'], hospitalSlots: [{ slug:'h12', visiting_days:['Mon','Wed','Fri'],           timing:'02:00 PM - 06:00 PM' }, { slug:'h02', visiting_days:['Tue','Thu'],                 timing:'10:00 AM - 02:00 PM' }] },
  { name: 'Dr. Meera Pillai',    specialization: 'Gynecologist',        experience: 22, education: 'MBBS, MS (OBG) — Grant Medical College Mumbai',    rating: 4.9, reviews_count: 720,  latitude: 19.032, longitude: 72.838, phone: '+91-98765-43217', consultation_fee: 900,  bio: 'High-risk pregnancy and laparoscopic surgery expert. 22 years of experience.',                        languages: ['English','Hindi','Malayalam','Marathi'], hospitalSlots: [{ slug:'h06', visiting_days:['Mon','Tue','Wed','Thu'], timing:'09:00 AM - 01:00 PM' }, { slug:'h04', visiting_days:['Fri','Sat'],           timing:'02:00 PM - 06:00 PM' }] },
  { name: 'Dr. Rajan Gupta',     specialization: 'Psychiatrist',        experience: 15, education: 'MBBS, MD (Psychiatry) — NIMHANS Bangalore',         rating: 4.6, reviews_count: 289,  latitude: 28.529, longitude: 77.221, phone: '+91-98765-43218', consultation_fee: 800,  bio: 'Specializes in depression, anxiety disorders, OCD, addiction psychiatry.',                            languages: ['English','Hindi','Kannada'],  hospitalSlots: [{ slug:'h03', visiting_days:['Wed','Thu','Fri','Sat'],    timing:'05:00 PM - 08:00 PM' }, { slug:'h12', visiting_days:['Mon','Tue'],                 timing:'11:00 AM - 02:00 PM' }] },
  { name: 'Dr. Nisha Verma',     specialization: 'Ophthalmologist',     experience: 10, education: 'MBBS, MS (Ophthalmology) — LV Prasad Eye Institute', rating: 4.7, reviews_count: 311, latitude: 13.060, longitude: 80.237, phone: '+91-98765-43219', consultation_fee: 700,  bio: 'LASIK specialist with expertise in cataract surgery, retinal diseases, and glaucoma.',                languages: ['English','Hindi','Telugu'],   hospitalSlots: [{ slug:'h01', visiting_days:['Mon','Wed','Fri'],           timing:'09:00 AM - 12:00 PM' }, { slug:'h11', visiting_days:['Tue','Thu','Sat'],           timing:'02:00 PM - 05:00 PM' }] },
  { name: 'Dr. Suresh Bhat',     specialization: 'ENT Specialist',      experience: 17, education: 'MBBS, MS (ENT) — Bombay Hospital Institute',        rating: 4.5, reviews_count: 256,  latitude: 19.006, longitude: 72.840, phone: '+91-98765-43220', consultation_fee: 700,  bio: 'Head & neck oncology surgeon. Expert in cochlear implants, sinus surgeries.',                         languages: ['English','Marathi','Konkani'],hospitalSlots: [{ slug:'h07', visiting_days:['Mon','Tue','Wed'],           timing:'10:00 AM - 01:00 PM' }, { slug:'h04', visiting_days:['Thu','Fri','Sat'],           timing:'03:00 PM - 07:00 PM' }] },
  { name: 'Dr. Ananya Das',      specialization: 'Endocrinologist',     experience: 13, education: 'MBBS, DM (Endocrinology) — SGPGI Lucknow',          rating: 4.8, reviews_count: 278,  latitude: 28.568, longitude: 77.210, phone: '+91-98765-43221', consultation_fee: 900,  bio: 'Type 1 & 2 diabetes specialist. Expert in thyroid disorders, PCOS, and hormonal imbalances.',         languages: ['English','Hindi','Bengali'],  hospitalSlots: [{ slug:'h09', visiting_days:['Tue','Thu'],                timing:'11:00 AM - 03:00 PM' }, { slug:'h03', visiting_days:['Mon','Wed','Fri'],            timing:'09:00 AM - 12:00 PM' }] },
  { name: 'Dr. Harish Kulkarni', specialization: 'General Physician',   experience: 24, education: 'MBBS, MD (Internal Medicine) — BJ Medical College', rating: 4.7, reviews_count: 830,  latitude: 19.130, longitude: 72.823, phone: '+91-98765-43222', consultation_fee: 400,  bio: 'Trusted family physician with 24 years. Preventive care and chronic disease management.',              languages: ['English','Hindi','Marathi','Kannada'], hospitalSlots: [{ slug:'h04', visiting_days:['Mon','Tue','Wed','Thu','Fri','Sat'], timing:'08:00 AM - 11:00 AM' }, { slug:'h05', visiting_days:['Sun'], timing:'10:00 AM - 01:00 PM' }] },
  { name: 'Dr. Pooja Saxena',    specialization: 'Dentist',             experience:  9, education: 'BDS, MDS (Orthodontics) — Maulana Azad Dental College', rating: 4.6, reviews_count: 394, latitude: 28.627, longitude: 77.371, phone: '+91-98765-43223', consultation_fee: 500, bio: 'Cosmetic and restorative dentist. Specialist in Invisalign, implants, and smile design.',             languages: ['English','Hindi'],            hospitalSlots: [{ slug:'h02', visiting_days:['Mon','Wed','Fri'],           timing:'02:00 PM - 06:00 PM' }] },
  { name: 'Dr. Ramesh Choudhary',specialization: 'Oncologist',          experience: 26, education: 'MBBS, DM (Medical Oncology) — Tata Memorial',       rating: 4.9, reviews_count: 1090, latitude: 19.006, longitude: 72.840, phone: '+91-98765-43224', consultation_fee: 2000, bio: 'World-renowned oncologist pioneering targeted therapy for breast, GI, and lung cancers.',             languages: ['English','Hindi','Gujarati'], hospitalSlots: [{ slug:'h07', visiting_days:['Mon','Tue','Wed','Thu','Fri'],timing:'09:00 AM - 05:00 PM' }, { slug:'h12', visiting_days:['Sat'],                      timing:'10:00 AM - 01:00 PM' }] },
  { name: 'Dr. Sneha Patil',     specialization: 'Cardiologist',        experience: 16, education: 'MBBS, DNB (Cardiology) — KEM Hospital',             rating: 4.7, reviews_count: 245,  latitude: 19.032, longitude: 72.838, phone: '+91-98765-43225', consultation_fee: 1100, bio: 'Non-invasive cardiologist specializing in echocardiography and heart failure management.',             languages: ['English','Marathi','Hindi'],  hospitalSlots: [{ slug:'h06', visiting_days:['Mon','Wed','Fri'],           timing:'10:00 AM - 02:00 PM' }, { slug:'h04', visiting_days:['Tue','Thu','Sat'],           timing:'04:00 PM - 08:00 PM' }] },
  { name: 'Dr. Vikas Singh',     specialization: 'Orthopedist',         experience: 21, education: 'MBBS, MS (Ortho) — GSMC Mumbai',                    rating: 4.8, reviews_count: 420,  latitude: 19.098, longitude: 72.842, phone: '+91-98765-43226', consultation_fee: 1000, bio: 'Spine surgery expert. Pioneer in minimally invasive spinal procedures.',                               languages: ['English','Hindi','Gujarati'], hospitalSlots: [{ slug:'h08', visiting_days:['Mon','Tue','Wed','Thu'],     timing:'09:00 AM - 01:00 PM' }, { slug:'h12', visiting_days:['Fri','Sat'],                 timing:'02:00 PM - 06:00 PM' }] },
  { name: 'Dr. Leena Shah',      specialization: 'Dermatologist',       experience: 14, education: 'MBBS, DDV — GMC Mumbai',                             rating: 4.5, reviews_count: 310,  latitude: 12.959, longitude: 77.649, phone: '+91-98765-43227', consultation_fee: 800,  bio: 'Laser dermatology and aesthetic medicine specialist. Expert in hair transplant and scar revision.',   languages: ['English','Gujarati','Marathi'],hospitalSlots: [{ slug:'h10', visiting_days:['Tue','Thu','Sat'],           timing:'01:00 PM - 05:00 PM' }] },
  { name: 'Dr. Pankaj Agarwal',  specialization: 'Urologist',           experience: 19, education: 'MBBS, MCh (Urology) — SGPGI Lucknow',               rating: 4.8, reviews_count: 356,  latitude: 28.440, longitude: 77.026, phone: '+91-98765-43228', consultation_fee: 1200, bio: 'Robotic surgeon for prostate, kidney, and bladder conditions.',                                        languages: ['English','Hindi'],            hospitalSlots: [{ slug:'h12', visiting_days:['Mon','Wed','Fri'],           timing:'09:00 AM - 01:00 PM' }, { slug:'h09', visiting_days:['Tue','Thu'],                 timing:'03:00 PM - 07:00 PM' }] },
  { name: 'Dr. Rekha Menon',     specialization: 'Gynecologist',        experience: 18, education: 'MBBS, DGO, DNB — Christian Medical College',          rating: 4.9, reviews_count: 560, latitude: 12.932, longitude: 79.133, phone: '+91-98765-43229', consultation_fee: 800,  bio: 'Specialist in fertility treatment, IVF, endometriosis, and minimal access surgery.',                  languages: ['English','Tamil','Malayalam'],hospitalSlots: [{ slug:'h11', visiting_days:['Mon','Wed','Fri'],           timing:'09:00 AM - 12:00 PM' }, { slug:'h06', visiting_days:['Tue','Thu','Sat'],           timing:'02:00 PM - 05:00 PM' }] },
  { name: 'Dr. Gaurav Mehrotra', specialization: 'Neurologist',         experience: 17, education: 'MBBS, DM (Neurology) — AIIMS Delhi',                 rating: 4.7, reviews_count: 298,  latitude: 28.568, longitude: 77.210, phone: '+91-98765-43230', consultation_fee: 1100, bio: 'Neurointerventionist specializing in stroke thrombolysis and movement disorders.',                      languages: ['English','Hindi'],            hospitalSlots: [{ slug:'h09', visiting_days:['Wed','Thu','Fri'],           timing:'02:00 PM - 06:00 PM' }, { slug:'h12', visiting_days:['Mon','Tue'],                 timing:'09:00 AM - 01:00 PM' }] },
  { name: 'Dr. Fatima Khan',     specialization: 'Pediatrician',        experience: 13, education: 'MBBS, DCH, DNB — Hinduja Hospital',                  rating: 4.8, reviews_count: 445,  latitude: 19.032, longitude: 72.838, phone: '+91-98765-43231', consultation_fee: 650,  bio: 'Pediatric pulmonologist with expertise in childhood asthma, allergies, and respiratory infections.',  languages: ['English','Hindi','Urdu'],     hospitalSlots: [{ slug:'h06', visiting_days:['Mon','Wed','Fri','Sat'],    timing:'10:00 AM - 02:00 PM' }, { slug:'h08', visiting_days:['Tue','Thu'],                 timing:'03:00 PM - 07:00 PM' }] },
  { name: 'Dr. Santosh Nair',    specialization: 'General Physician',   experience: 16, education: 'MBBS, MD (Internal Medicine) — KEM Hospital',         rating: 4.6, reviews_count: 510, latitude: 19.050, longitude: 72.832, phone: '+91-98765-43232', consultation_fee: 500,  bio: 'General medicine expert with special interest in infectious diseases and hypertension.',              languages: ['English','Malayalam','Marathi'],hospitalSlots: [{ slug:'h05', visiting_days:['Mon','Tue','Wed','Thu','Fri'],timing:'08:30 AM - 12:30 PM' }] },
  { name: 'Dr. Deepak Sharma',   specialization: 'Pulmonologist',       experience: 15, education: 'MBBS, MD — PGIMER Chandigarh',                       rating: 4.5, reviews_count: 234,  latitude: 28.627, longitude: 77.371, phone: '+91-98765-43233', consultation_fee: 750,  bio: 'Expert in sleep disorders, COPD, asthma management, and interventional pulmonology.',                 languages: ['English','Hindi','Punjabi'],  hospitalSlots: [{ slug:'h02', visiting_days:['Mon','Thu','Sat'],           timing:'11:00 AM - 03:00 PM' }, { slug:'h03', visiting_days:['Tue','Wed'],                 timing:'04:00 PM - 07:00 PM' }] },
  { name: 'Dr. Anita Reddy',     specialization: 'Ophthalmologist',     experience: 12, education: 'MBBS, DO, DNB — LV Prasad Eye Institute',             rating: 4.7, reviews_count: 289, latitude: 12.959, longitude: 77.649, phone: '+91-98765-43234', consultation_fee: 750,  bio: 'Paediatric ophthalmologist and cornea specialist. Expert in squint correction.',                      languages: ['English','Telugu','Kannada'], hospitalSlots: [{ slug:'h10', visiting_days:['Tue','Thu','Sat'],           timing:'09:00 AM - 12:00 PM' }, { slug:'h11', visiting_days:['Mon','Wed','Fri'],           timing:'02:00 PM - 05:00 PM' }] },
  { name: 'Dr. Mohan Rajan',     specialization: 'ENT Specialist',      experience: 20, education: 'MBBS, MS (ENT) — CMC Vellore',                        rating: 4.8, reviews_count: 334, latitude: 12.932, longitude: 79.133, phone: '+91-98765-43235', consultation_fee: 800,  bio: 'Head and neck cancer surgeon with subspecialty in skull base surgery.',                               languages: ['English','Tamil'],            hospitalSlots: [{ slug:'h11', visiting_days:['Mon','Tue','Wed','Thu'],    timing:'09:00 AM - 12:00 PM' }] },
  { name: 'Dr. Prashant Borkar', specialization: 'Psychiatrist',        experience: 12, education: 'MBBS, MD (Psychiatry) — Seth GS Medical College',    rating: 4.5, reviews_count: 198,  latitude: 19.098, longitude: 72.842, phone: '+91-98765-43236', consultation_fee: 700,  bio: 'Specializes in adolescent psychiatry, trauma therapy, bipolar disorders.',                            languages: ['English','Marathi','Hindi'],  hospitalSlots: [{ slug:'h08', visiting_days:['Wed','Thu','Fri','Sat'],    timing:'04:00 PM - 08:00 PM' }] },
  { name: 'Dr. Neha Agarwal',    specialization: 'Endocrinologist',     experience: 10, education: 'MBBS, MD, DM — Manipal Hospital',                     rating: 4.7, reviews_count: 212, latitude: 12.959, longitude: 77.649, phone: '+91-98765-43237', consultation_fee: 850,  bio: 'Diabetologist and thyroid specialist using cutting-edge CGM technology.',                             languages: ['English','Hindi','Kannada'],  hospitalSlots: [{ slug:'h10', visiting_days:['Mon','Wed','Fri'],           timing:'10:00 AM - 01:00 PM' }] },
  { name: 'Dr. Ravi Shankar',    specialization: 'Urologist',           experience: 14, education: 'MBBS, MS, MCh — AIIMS Bhopal',                        rating: 4.6, reviews_count: 278, latitude: 28.529, longitude: 77.221, phone: '+91-98765-43238', consultation_fee: 1000, bio: 'Uro-oncologist specializing in laparoscopic and robotic procedures for kidney and prostate cancer.',  languages: ['English','Hindi'],            hospitalSlots: [{ slug:'h03', visiting_days:['Tue','Thu','Sat'],           timing:'10:00 AM - 02:00 PM' }, { slug:'h09', visiting_days:['Mon','Wed'],                 timing:'01:00 PM - 05:00 PM' }] },
  { name: 'Dr. Smita Kulkarni',  specialization: 'Oncologist',          experience: 18, education: 'MBBS, MD (Radiation Oncology) — Tata Memorial',       rating: 4.8, reviews_count: 456, latitude: 19.006, longitude: 72.840, phone: '+91-98765-43239', consultation_fee: 1500, bio: 'Radiation oncologist with expertise in stereotactic radiosurgery, IGRT, and palliative care.',       languages: ['English','Marathi','Hindi'],  hospitalSlots: [{ slug:'h07', visiting_days:['Mon','Wed','Fri'],           timing:'10:00 AM - 04:00 PM' }] },
];

// ── Seed function ─────────────────────────────────────────────────────────────
const seed = async () => {
  // Clear existing data
  await Hospital.deleteMany({});
  await Doctor.deleteMany({});
  console.log('🗑️  Cleared existing collections');

  // Insert hospitals and build a slug → ObjectId map
  const insertedHospitals = await Hospital.insertMany(
    hospitalData.map(({ slug, ...rest }) => rest)
  );

  // Build lookup: slug → ObjectId
  const slugToId = {};
  hospitalData.forEach(({ slug }, i) => {
    slugToId[slug] = insertedHospitals[i]._id;
  });
  console.log(`✅ Inserted ${insertedHospitals.length} hospitals`);

  // Build doctor documents with resolved ObjectIds
  const doctorDocs = doctorData.map(({ hospitalSlots, ...rest }) => ({
    ...rest,
    hospitals: hospitalSlots
      .filter(({ slug }) => slugToId[slug]) // guard against bad slugs
      .map(({ slug, visiting_days, timing }) => ({
        hospital:      slugToId[slug],
        visiting_days,
        timing,
      })),
  }));

  await Doctor.insertMany(doctorDocs);
  console.log(`✅ Inserted ${doctorDocs.length} doctors with hospital associations`);
  console.log('🎉 Seeding complete!');
};

// ── Entry point ───────────────────────────────────────────────────────────────
const run = async () => {
  try {
    await connectDB();
    await seed();
    if (require.main === module) process.exit(0);
  } catch (err) {
    console.error('❌ Seeding error:', err.message);
    if (require.main === module) process.exit(1);
    else throw err;
  }
};

module.exports = run;
if (require.main === module) run();
